name: app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  share_plus: ^10.1.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.8.0
  top_snackbar_flutter: ^3.1.0
  provider: ^6.1.2
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  flutter_gen_runner: ^5.8.0

flutter:

  uses-material-design: true
  
  assets:
    - .env

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
