name: app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  share_plus: ^10.1.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.8.0
  top_snackbar_flutter: ^3.1.0
  provider: ^6.1.2
  nested: ^1.0.0
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  flutter_gen_runner: ^5.8.0

flutter:

  uses-material-design: true
  
  assets:
    - .env
    - assets/icon/
    - assets/images/
    - assets/png/
    - assets/svg/

  fonts:
  - family: Urbanist
    fonts:
    - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
      weight: 400
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
      weight: 500
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
      weight: 600
      style: normal
    - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
      weight: 700
      style: normal
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
